#!/usr/bin/env python3
"""Inserts an "Old version" note into the old Radio workflows (and into the archive a
Documentation note).

These workflows are not generated by the construction tool (copies, backups, the
archive of the first version). They should still be explained in the interface,
what they are - otherwise one guesses when opening them. Only ONE additional
warning note above the surface is changed; nodes, connections and texts remain untouched.

Usage:  python3 altfassungen-note.py [--dry-run]
"""
from __future__ import annotations

import json
import subprocess
import sys
import tempfile
from pathlib import Path
from uuid import uuid4

CFG = "~/.ssh/config"
CT = "103"
NAME = "Documentation Note"

# (identifier, title of the note, lines)
LISTE = [
    ("7Vv3NSFsS7OZaBSd", "Old version: Intermediate V2.0", [
        "Intermediate from the renovation phase (20.09.2026) - NOT in operation.",
        "In operation is the process “Radio - Telegram-Agent” (RadioAgentBot).",
        "Kept for illustration; description of versions: VERSIONS.md.",
        "Backups are located under sicherungen/radio-fassungen/ (outside the project).",
    ]),
    ("zxBICXCfUaMGhNmT", "Old version: Copy of an intermediate state", [
        "Copy from the renovation phase - NOT in operation.",
        "In operation is the process “Radio - Telegram-Agent” (RadioAgentBot).",
        "Can be deleted if the backups under sicherungen/radio-fassungen/ are sufficient.",
    ]),
    ("jt2IC4TVPTF1KDLp", "Alternative version: Copy of the wish bot", [
        "Old copy of the wish bot (first version) - NOT in operation.",
        "In operation is the process “Radio - Telegram-Agent” (RadioAgentBot).",
        "Description: BAU.md (v1-v9); Backups: sicherungen/radio-fassungen/.",
    ]),
    ("da7f06de-0bcf-4fbe-8c8d-ad8927d3d509", "Old version: as of before the refactoring", [
        "Backup of the version BEFORE the refactoring (19.09.2026) - NOT in operation.",
        "This allows viewing the state from back then; in operation is RadioAgentBot.",
        "Description: BAU.md; Backups: sicherungen/radio-fassungen/.",
    ]),
    ("RadioTelegramBot", "Old version: Radio - Telegram wish bot", [
        "The wish bot of the first version (until 19.09.2026) - NOT in operation.",
        "Replaced by the “Radio - Telegram-Agent” (Stages 0-3, Tools, Mailbox).",
        "Its tools are now located in “Tool - Radio” and “Tool - Messages”.",
        "Description: BAU.md (v1-v9), HANDBUCH.md.",
    ]),
    ("iDfPikpAIqTO9XQ2", "Alternative version: Copy of the wish bot", [
        "Copy of the wish bot of the first version - NOT IN OPERATION.",
        "In operation is the process “Radio - Telegram-Agent” (RadioAgentBot).",
        "Description: BAU.md (v1-v9).",
    ]),
    ("RadioTelegramBot-Archiv-2026-09-19", "Alternative version: Backup 19.09.2026", [
        "Backup of the wish bot from 19.09.2026 - NOT IN OPERATION.",
        "Kept, in case the state from back then is needed.",
        "Description: BAU.md; Backups: sicherungen/radio-fassungen/.",
    ]),
    ("RadioWerkzeugSuche", "Alternative version: Tool - Search for title", [
        "Single tool process of the first version - NOT IN OPERATION.",
        "This task is today in the process “Tool - Radio” (three branches in one process).",
        "Description: HANDBUCH.md, HANDBUCH.md.",
    ]),
    ("RadioWerkzeugRichtung", "Alternative version: Tool - Search for direction", [
        "Single tool process of the first version - NOT IN OPERATION.",
        "This task is currently in the “Tool - Radio” workflow.",
        "Description: HANDBUCH.md, HANDBUCH.md.",
    ]),
    ("RadioWerkzeugSofort", "Old version: Tool - Play now", [
        "Single tool process of the first version - NOT IN OPERATION.",
        "This task is currently in the “Tool - Radio” workflow.",
        "Description: HANDBUCH.md, HANDBUCH.md.",
    ]),
    ("RadioWerkzeugDanach", "Old version: Tool - Play later", [
        "Single tool process of the first version - NOT IN OPERATION.",
        "This task is currently in the “Tool - Radio” workflow.",
        "Description: HANDBUCH.md, HANDBUCH.md.",
    ]),
    ("RadioWerkzeugStatus", "Old version: Tool - What’s playing", [
        "Single tool process of the first version - NOT IN OPERATION.",
        "This task is currently in the “Tool - Radio” workflow.",
        "Description: HANDBUCH.md, HANDBUCH.md.",
    ]),
    ("bjFSfXGqpLg7AAXw", "Radio - AI-Moderator (Archive)", [
        "First version of moderation: Generate text, speak it, put it into the stream.",
        "Not in operation - in operation the agent (RadioAgentBot) moderates via the radio-tts service.",
        "Frame and labels: werkzeuge/archiv-frames.py (not in construction tool).",
        "Description: BAU.md, HANDBUCH.md, ANHANG/n8n-oberflaeche.html (Section 16).",
    ]),
]


def ssh(command: str) -> str:
    done = subprocess.run(["ssh", "-F", CFG, "-o", "BatchMode=yes", "ai-server", command],
                            capture_output=True, text=True, check=False)
    if done.returncode:
        raise RuntimeError(done.stderr.strip()[:300])
    return done.stdout


def fetch(identifier: str) -> dict:
    raw = ssh("pct exec %s -- bash -lc 'docker exec -u node n8n n8n export:workflow "
              "--id=%s --output=/tmp/w.json >/dev/null 2>&1; docker exec n8n cat /tmp/w.json'"
              % (CT, identifier))
    data = json.loads(raw)
    return data


def note(data: dict, title: str, lines: list[str]) -> dict:
    workflow = data[0] if isinstance(data, list) else data
    workflow["nodes"] = [k for k in workflow["nodes"]
                       if not (k["type"] == "n8n-nodes-base.stickyNote" and k["name"] == NAME)]
    nodes = [k for k in workflow["nodes"] if k["type"] != "n8n-nodes-base.stickyNote"]
    x0 = min(k["position"][0] for k in nodes)
    y0 = min(k["position"][1] for k in workflow["nodes"])
    height = 40 + 22 * len(lines)
    workflow["nodes"].append({
        "parameters": {"content": "## " + title + "\n" + "\n".join(lines),
                       "height": height, "width": 1150, "color": 2},
        "id": str(uuid4()), "name": NAME,
        "type": "n8n-nodes-base.stickyNote", "typeVersion": 1,
        "position": [x0, y0 - height - 80],
    })
    return workflow


def deploy(workflow: dict) -> None:
    with tempfile.NamedTemporaryFile("w", suffix=".json", delete=False, encoding="utf-8") as f:
        json.dump(workflow, f, ensure_ascii=False, indent=2)
        path = f.name
    text = Path(path).read_text(encoding="utf-8")
    subprocess.run(["ssh", "-F", CFG, "-o", "BatchMode=yes", "ai-server",
                    "pct exec %s -- bash -c 'cat > /tmp/w-new.json'" % CT],
                   input=text, text=True, check=True)
    ssh("pct exec %s -- bash -lc 'docker cp /tmp/w-new.json n8n:/tmp/ >/dev/null && "
        "docker exec -u node n8n n8n import:workflow --input=/tmp/w-new.json'" % CT)


def main() -> int:
    dry = "--dry-run" in sys.argv
    for identifier, title, lines in LISTE:
        try:
            workflow = note(fetch(identifier), title, lines)
        except Exception as reason:  # noqa: BLE001
            print(f" ERROR {identifier}: {reason}")
            continue
        state = f"active={workflow.get('active')} archived={workflow.get('isArchived')}"
        print(f"  {identifier:38s} {workflow.get('name')[:36]:38s} {state}")
        if not dry:
            deploy(workflow)
    return 0


if __name__ == "__main__":
    sys.exit(main())
