#!/usr/bin/env python3
"""Creates frame and labels in the archive workflow "Radio - AI-Moderator".

The archive workflow originates from the first version and is not generated by the building tool
- therefore it has neither frames nor notes. This tool adds them
(additive: no nodes, no connections, no logic text is changed).

Call:  python3 archiv-frames.py <workflow.json> <target.json>
Then:  docker exec -u node n8n n8n import:workflow --input=<target.json>
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

# Areas: (Frame name, Title+Description, Color, Nodes)
AREAS = [
    ("Note Inputs",
     "## Inputs\nStarted by hand, via form or from outside - everything runs in"
     "the same chain.",
     4, ["Manuell", "Formular", "Webhook"]),
    ("Note Context",
     "## Context\nWhat is currently running, and what happened last? This is the basis"
     "for the moderation text.",
     5, ["Felder", "Currently running", "Recherche"]),
    ("Note Text and Voice",
     "## Text and Voice\nFrom the context a speech text is generated, from which a finished file is created.",
     6, ["Moderationstext", "Text clean", "voice", "Filename"]),
    ("Note Output",
     "## Output\nEither speak live (interrupts the program briefly) or upload"
     "(then runs as a separate title).",
     7, ["Modus", "Live speaking", "Hochladen"]),
    ("Note Tracking",
     "## Tracking\nAfter uploading: wait, find the title in the archive, assign the"
     "wish and hand it over.",
     3, ["Warten", "Find title", "Zuordnen", "Place wish", "Answer"]),
    ("Note Old Tools",
     "## Old Tools\nRemnants of the first version - not connected, only for"
     "Erinnerung.",
     2, ["Select hit"]),
]

NOTIZEN = {
    "Manuell": "start by hand (test run).",
    "Formular": "start via the n8n form: title, wish text, voice.",
    "Webhook": "start from outside (schedule or external tool).",
    "Felder": "Collect inputs: title, wish text, voice, announcement yes/no.",
    "Currently running": "What is currently running on the station? (AzuraCast)",
    "Recherche": "Collect messages and context for moderation.",
    "Moderationstext": "Generate the speech text from the language model (Ollama).",
    "Text clean": "Prepare speech text: left, emojis, abbreviations, sentence boundaries.",
    "voice": "Create language (Piper in radio-tts service).",
    "Filename": "Build filename of announcement.",
    "Modus": "Yes = live speaking, no = upload.",
    "Live speaking": "Speak the announcement live into the DJ harbor.",
    "Hochladen": "Upload the announcement as title (way without interruption).",
    "Warten": "Wait until the broadcaster has processed the title.",
    "Find title": "Search for the freshly uploaded title in the archive.",
    "Zuordnen": "Assign wish and found title to each other.",
    "Place wish": "Submit the wish to the broadcaster.",
    "Answer": "Build response for the caller.",
    "Select hit": "Old helper: select first hit of the search (no longer connected).",
}

# Node size as in anordnung-check.py
GROESSE = {"n8n-nodes-base.if": (200, 110), "n8n-nodes-base.switch": (230, 110)}
RAND_X, RAND_OBEN, RAND_UNTEN = 70, 80, 60


def groesse(nodes: dict) -> tuple[int, int]:
    return GROESSE.get(nodes["type"], (110, 110))


def main() -> int:
    source, target = Path(sys.argv[1]), Path(sys.argv[2])
    rohdaten = json.loads(source.read_text(encoding="utf-8"))
    workflow = rohdaten[0] if isinstance(rohdaten, list) else rohdaten
    nach_name = {k["name"]: k for k in workflow["nodes"]}
    missing = [n for _, _, _, names in AREAS for n in names if n not in nach_name]
    if missing:
        raise SystemExit(f"Nodes missing in the process: {missing}")

    # Remove old frames (only sticky note - logic remains untouched)
    workflow["nodes"] = [k for k in workflow["nodes"]
                       if k["type"] != "n8n-nodes-base.stickyNote"]

    # 1) Calculate raw boxes per area
    kaesten = []
    for name, text, farbe, names in AREAS:
        xs0 = min(nach_name[n]["position"][0] for n in names)
        ys0 = min(nach_name[n]["position"][1] for n in names)
        xs1 = max(nach_name[n]["position"][0] + groesse(nach_name[n])[0] for n in names)
        ys1 = max(nach_name[n]["position"][1] + groesse(nach_name[n])[1] for n in names)
        kaesten.append({"name": name, "text": text, "farbe": farbe,
                        "kx0": xs0, "kx1": xs1, "ky0": ys0, "ky1": ys1,
                        "x0": xs0 - RAND_X, "x1": xs1 + RAND_X,
                        "y0": ys0 - RAND_OBEN, "y1": ys1 + RAND_UNTEN})

    # 2) Horizontally crop where areas meet in height - otherwise
    # the frames overlap (the nodes are only 200 units apart).
    for a in kaesten:
        for b in kaesten:
            if a is b:
                continue
            trifft_hoehe = a["y0"] < b["y1"] and b["y0"] < a["y1"]
            if not trifft_hoehe:
                continue
            if a["kx1"] <= b["kx0"]:                      # a lies to the left of b
                a["x1"] = min(a["x1"], b["x0"] - 8)
            elif b["kx1"] <= a["kx0"]:                    # b lies to the left of a
                a["x0"] = max(a["x0"], b["x1"] + 8)

    for k in kaesten:
        if k["x0"] > k["kx0"] or k["x1"] < k["kx1"] or k["y0"] > k["ky0"] or k["y1"] < k["ky1"]:
            raise SystemExit(f"Frame calculated too small: {k['name']}")
        workflow["nodes"].append({
            "parameters": {
                "content": k["text"],
                "height": k["y1"] - k["y0"],
                "width": k["x1"] - k["x0"],
                "color": k["farbe"],
            },
            "id": "notiz-" + k["name"].split()[-1].lower(),
            "name": k["name"],
            "type": "n8n-nodes-base.stickyNote",
            "typeVersion": 1,
            "position": [k["x0"], k["y0"]],
        })
        print(f" Frame {k['name']:26s} x {k['x0']}..{k['x1']}  y {k['y0']}..{k['y1']}")

    for name, notiz in NOTIZEN.items():
        nach_name[name]["notes"] = notiz
        nach_name[name]["notesInFlow"] = True
    print(f" Labels: {len(NOTIZEN)} nodes")

    target.write_text(json.dumps(rohdaten if isinstance(rohdaten, list) else workflow,
                               ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Written: {target}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
