#!/usr/bin/env python3
"""Inserts a documentation note into any n8n workflow.

Intended for workflows that are NOT generated by the construction tool (old versions,
safeguards, archive). The note lies above the entire area, thus
not touching any frame; nodes, connections and texts remain untouched.

Call:
  python3 docs-note.py <eingabe.json> <target.json> <title> <zeile1> [zeile2 ...]

Then import:
  docker cp <target.json> n8n:/tmp/w.json
  docker exec -u node n8n n8n import:workflow --input=/tmp/w.json
"""
from __future__ import annotations

import json
import sys
from uuid import uuid4
from pathlib import Path

NAME = "Documentation Note"
BREITE = 1150
MARGIN = 80


def main() -> int:
    if len(sys.argv) < 5:
        raise SystemExit(__doc__)
    source, target, title = Path(sys.argv[1]), Path(sys.argv[2]), sys.argv[3]
    lines = sys.argv[4:]

    raw = json.loads(source.read_text(encoding="utf-8"))
    workflow = raw[0] if isinstance(raw, list) else raw

    # Creating a second one would be unnecessary - replace the old version of the note.
    workflow["nodes"] = [k for k in workflow["nodes"]
                       if not (k["type"] == "n8n-nodes-base.stickyNote" and k["name"] == NAME)]

    nodes = [k for k in workflow["nodes"] if k["type"] != "n8n-nodes-base.stickyNote"]
    if not nodes:
        raise SystemExit("The workflow has no nodes.")
    x0 = min(k["position"][0] for k in nodes)
    y0 = min(k["position"][1] for k in workflow["nodes"])
    height = 40 + 22 * len(lines)
    workflow["nodes"].append({
        "parameters": {
            "content": "## " + title + "\n" + "\n".join(lines),
            "height": height,
            "width": BREITE,
            "color": 2,
        },
        "id": str(uuid4()),
        "name": NAME,
        "type": "n8n-nodes-base.stickyNote",
        "typeVersion": 1,
        "position": [x0, y0 - height - MARGIN],
    })
    target.write_text(json.dumps(raw if isinstance(raw, list) else workflow,
                               ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"  {workflow.get('name')}: note set at [{x0}, {y0 - height - MARGIN}]")
    return 0


if __name__ == "__main__":
    sys.exit(main())
